name: Exampol for Continuous Deployment for Local

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Simulated Deploy Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build app
        run: yarn build

      - name: Simulate deploy step
        run: echo "✅ Despliegue simulado completado correctamente."
